name: anchr_android
description: Android client for Anchr.io link collections

version: 1.0.16+17

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.12.0+1
  url_launcher: 5.0.0
  flutter_svg: ^0.13.0+2
  shared_preferences: ^0.4.3
  sqflite: ^1.1.0
  fluttertoast: ^3.0.3
  package_info: ^0.4.0+6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/no_content.svg
    - assets/loading.svg
    - assets/launcher_icon.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icon.png"