name: anchr_android
description: Android client for Anchr.io link collections

version: 1.1.4+26

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  http: ^0.12.2
  url_launcher: ^5.7.8
  flutter_svg: ^0.19.1
  shared_preferences: ^0.5.10
  sqflite: ^1.3.1+1
  fluttertoast: ^7.0.2
  package_info: ^0.4.3
  f_logs: ^1.2.2
  device_info: ^0.4.2+7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/no_content.svg
    - assets/loading.svg
    - assets/launcher_icon.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icon.png"