name: anchr_android
description: Android client for Anchr.io link collections

version: 1.2.1+29

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  http: ^0.13.0
  url_launcher: ^6.0.2
  flutter_svg: ^0.19.1
  shared_preferences: ^0.5.12+4
  sqflite: ^2.0.0+3
  fluttertoast: ^7.0.2
  package_info: ^2.0.0
  f_logs: ^1.2.2
  device_info: ^2.0.0
  share: 2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1

flutter:
  uses-material-design: true

  assets:
    - assets/no_content.svg
    - assets/loading.svg
    - assets/launcher_icon.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icon.png"